### ISSUE TITLE
Demo with ReactJs

### ISSUE THREAD

**Issue by thiagolocatelli** [ahiipsa/navigation#1]
Would you be able to create a demo using ReactJS? like the tv_app but with react.

**Comment by ahiipsa** [comment]
Hello @thiagolocatelli,
Sorry, i don't have a time

**Comment by thiagolocatelli** [comment]
Trying to use your library with React. It wont work because you are using custom html Tags. Renaming from nv-\* to data-nv-\* or aria-nv-\*  would work.

**Comment by thiagolocatelli** [comment]
Its working now. Sorry!
