### ISSUE TITLE
Navigate from last element in row to last element in next row with key down

### ISSUE THREAD

**Issue by davorsm** [ahiipsa/navigation#7]
I am working on a smart tv project and i have a problem with navigation. When i want to go from last element in a row with key down, if there is no element under it, navigation doesn't do anything. We have a request that if there is no element under current element, on key down, it should navigate to last element in next row.
https://s27.postimg.org/os2jq4dvn/Capture.png

Please help

**Comment by ahiipsa** [comment]
Hello, sorry, i don't thought about this case.

But, you may add special attr for nav-element or scope-element:
- nv-scope-fov
- nv-el-fov

example with `nv-scope-fov`, it expands the field of view for all elements in scope:
```html
<div nv-scope nv-scope-fov="180">
     // elements
</div>
```

**Comment by dds111** [comment]
Did you mean like this?

https://s23.postimg.org/fga3x6akr/kod.png

That did not help.

**Comment by ahiipsa** [comment]
what version do you use?

**Comment by dds111** [comment]
I updated to latest version and now it is working.. Thanks. Could you tell me how can i set current element without deleting nv-el-current attribute from an element and setting it to another and restart navigation?

**Comment by ahiipsa** [comment]
```js
var element = document.getElementById('someId');
var scope = navigation.getScope('scope2')
scope.setCurrentElement(element);
```
